name: CI/CD to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGION: us-central1
  REPO_NAME: testcontainer
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}/testcontainer:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth login
        gcloud auth configure-docker ${REGION}-docker.pkg.dev
        gcloud auth list
        gcloud config list

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .
        docker push ${{ env.IMAGE_NAME }}

    - name: Deploy to Compute Engine (if needed)
      run: |
        gcloud compute instances update-container ${{ secrets.GCE_INSTANCE_NAME }} \
          --zone ${{ secrets.GCE_ZONE }} \
          --container-image ${{ env.IMAGE_NAME }}

    - name: Verify deployment
      run: |
        sleep 30
        EXTERNAL_IP=$(gcloud compute instances describe ${{ secrets.GCE_INSTANCE_NAME }} --zone ${{ secrets.GCE_ZONE }} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        curl -X POST http://$EXTERNAL_IP:5000/optimize -H 'Content-Type: application/json' -d '{}' -v