name: CI/CD to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: testcontainer
  REGISTRY_HOSTNAME: us-central1-docker.pkg.dev

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t $REGISTRY_HOSTNAME/$PROJECT_ID/testcontainer/$IMAGE:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: docker push $REGISTRY_HOSTNAME/$PROJECT_ID/testcontainer/$IMAGE:$GITHUB_SHA
